### ISSUE TITLE
scase with aliased module names

### ISSUE THREAD

**Issue by Daevor** [Qqwy/elixir_solution#2]
I’m running into a slight problem with `scase `and `alias`ed module names. I’m not sure if I’m doing something wrong. Here follows a simple test case to demonstrate the issue.

First I define a simple module:

```
iex(1)> defmodule Domain.Module1 do
...(1)>   def wrap(something) do
...(1)>     {:ok, something}
...(1)>   end
...(1)> end
```
Then alias it and ensure the alias works:

```
iex(5)> alias Domain.Module1
Domain.Module1
iex(6)> Module1.wrap("asdf")
{:ok, "asdf"}
```
Now we test with a normal case statement:

```
iex(7)> case Module1.wrap("asdf") do
...(7)> 
...(7)>   {:ok, stuff} -> "All good in the 'hood: #{stuff}"
...(7)> 
...(7)>   _ -> "Ehh... what happened?"
...(7)> 
...(7)> end
"All good in the 'hood: asdf"
```
All fine so far. Now the equivalent scase:

```
iex(9)> import Solution
Solution
iex(10)> scase Module1.wrap("asdf") do
...(10)> 
...(10)>   ok(stuff) -> "All good in the 'hood: #{stuff}"
...(10)> 
...(10)>   _ -> "Ehh... what happened?"
...(10)> 
...(10)> end
** (UndefinedFunctionError) function Module1.wrap/1 is undefined (module Module1 is not available)
    Module1.wrap("asdf")
iex(10)>
```

**Comment by Qqwy** [comment]
Thank you very much for your issue! 
This seems like a bug on Solution's part. There probably is an oversight somewhere in the (hygienic) macro implementation.
I'll try to reproduce it and then solve it. I'll keep you updated :slightly_smiling_face: .
